###Get all books
GET http://localhost:3000/books

###Get one book by ID
GET http://localhost:3000/books/1

###Create a book using POST
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "Computer Science",
  "author": "Alan Turing",
  "isbn": "78432787865374",
  "publication_year": 1930
}

###Update a book using Patch
PATCH http://localhost:3000/books/3
Content-Type: application/json

{
  "title": "Computer Science"
}

###Delete a book
DELETE http://localhost:3000/books/2

### count books by year
GET http://localhost:3000/books/count/1930